title: My Writing
github_user: MomoSolaris8
github_repo: myblog
description: ""
baseurl: ""
url: ""
permalink: /:year/:month/:day/:title/

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .github/
  - vendor/
  - save-server.py
  - start.sh
